In [2]:
import numpy
from matplotlib import pyplot

In [1]:
#problem parameters in N and mm
E = 210e6
P = 20e3
#L = 2e3
I = 60e-6
n = 3
dl = 2

In [3]:
def elemstiff(E,I,L):    
#     Bmat = numpy.matrix([[7,1,-8],[1,7,-8],[-8,-8,16]])
#     k = E*A/(3*L) * Bmat
#     return k
    Bmat = [[12,6*L,-12,6*L],[6*L,4*L*L,-6*L,2*L*L],[-12,-6*L,12,-6*L],[6*L,2*L*L,-6*L,4*L*L]]
    k = []
    for i in range(len(Bmat)):
        B = Bmat[i]
        k_sub = []
        for j in range(len(B)):
            k_sub.append(Bmat[i][j] * E*I/L**3)
        k.append(k_sub)
    return k

In [4]:
k = []
for i in range(n-1):
    k.append(elemstiff(E,I,dl))
k

[[[18900.0, 18900.0, -18900.0, 18900.0],
  [18900.0, 25200.0, -18900.0, 12600.0],
  [-18900.0, -18900.0, 18900.0, -18900.0],
  [18900.0, 12600.0, -18900.0, 25200.0]],
 [[18900.0, 18900.0, -18900.0, 18900.0],
  [18900.0, 25200.0, -18900.0, 12600.0],
  [-18900.0, -18900.0, 18900.0, -18900.0],
  [18900.0, 12600.0, -18900.0, 25200.0]]]

In [5]:
K = numpy.zeros(shape=(2*n,2*n))    #multiplied by 2 because 2 degrees of freedom per node
x = 0
for X in range (0,n,2):           #X is to get the location in the global matrix to add the element matrix
    c = 0
    for C in range (X,X+4):
        r = 0
        for R in range (X,X+4):
            K[C][R] = K[C][R] + k[x][r][c]
            r = r + 1
        c = c + 1
    x = x + 1
K

array([[ 18900.,  18900., -18900.,  18900.,      0.,      0.],
       [ 18900.,  25200., -18900.,  12600.,      0.,      0.],
       [-18900., -18900.,  37800.,      0., -18900.,  18900.],
       [ 18900.,  12600.,      0.,  50400., -18900.,  12600.],
       [     0.,      0., -18900., -18900.,  18900., -18900.],
       [     0.,      0.,  18900.,  12600., -18900.,  25200.]])

In [25]:
F = [[0],[0],[-P],[0],[0],[0]]
F[2]

[-20000.0]

In [23]:
#elimination
#Displacement for rows 1,2 and 5 should be eliminated

Kelim =K[numpy.ix_([2,3,5],[2,3,5])]
#^from row index 2,3,5 take element index 2,3,5
Kelim

array([[37800.,     0., 18900.],
       [    0., 50400., 12600.],
       [18900., 12600., 25200.]])

In [30]:
f = numpy.matrix([F[2],F[3],F[5]])
f

matrix([[-20000.],
        [     0.],
        [     0.]])

In [31]:
Kinv = numpy.linalg.inv(numpy.matrix(Kelim))
U = Kinv*f
U

matrix([[-0.92592593],
        [-0.1984127 ],
        [ 0.79365079]])

In [46]:
u = numpy.zeros((6,1))
nocons = [2,3,5]
ni = 0
for i in nocons:
    u[i] = U[n]
    ni=ni+1
u
#displacements in mm

IndexError: index 3 is out of bounds for axis 0 with size 3

In [41]:
F = K*numpy.matrix(u)
F
#forces in N

matrix([[ 13750.],
        [ 15000.],
        [-20000.],
        [     0.],
        [  6250.],
        [     0.]])

In [45]:
for i in range (0,2*n,2):
    elemU[] = numpy.array(U[i:i+4])


array([], shape=(0, 1), dtype=float64)