In [1]:
import numpy
from matplotlib import pyplot
import math

In [2]:
def elemlength(n1,n2):
    l = numpy.sqrt((n2[0]-n1[0])**2 + (n2[1]-n1[1])**2)
    return l

In [3]:
def angle(n1,n2):
    t = math.atan((n2[1]-n1[1])/(n2[0]-n1[0])) * 180 / math.pi
    if(t<0):
        t = 180 + t
    return t

In [4]:
def elemstiff(E,A,L, theta):
#PlaneTrussElementStiffness This function returns the element
#stiffness matrix for a plane truss
#element with modulus of elasticity E,
#cross-sectional area A, length L, and
#angle theta (in degrees).
#The size of the element stiffness
#matrix is 4 x 4.
    x = theta*math.pi/180
    C = math.cos(x)
    S = math.sin(x)
    y = [[C*C, C*S, C*-C, C*-S], [C*S, S*S, C*-S, S*-S], [C*-C, C*-S, C*C, C*S], [C*-S, S*-S, C*S, S*S]]
    k = E*A/L*numpy.array(y)
    return k

In [5]:
def Globalstiff(K,k,i,j):
#PlaneTrussAssemble This function assembles the element stiffness matrices into a global stiffness matrix
    x = [i,j]
    y = [i,j]
    c = 0
    for x1 in x:
        c0 = 0
        for y1 in y:
            c1 = c
            for x0 in range (x1*2,x1*2+2):
                c2 = c0
                for y0 in range (y1*2,y1*2+2):
                    K[x0][y0] = K[x0][y0] + k[c1][c2]
                    c2=c2+1
                c1=c1+1
            c0=c0+2
        c=c+2

# the element stiffness matrix is grouped into 4 element subsquares 
# which are then placed in the corresponding locations in the global stiffness matrix based on nodal connectivity
# c1 and c2 represent the iteration indices for the subsquares, c and c0 represent theindices to iterate though the sub squares.
# similarly x0 and y0 are the iteration indices where the subsquares will be added in the global stiffness matrix
# x1 and y1 implement nodal connectivity into the assembly

In [7]:
E = 210e6
P = 20e3
A = 1e-4
L =[]
T =[]
k =[]
K = numpy.zeros(shape=(2*3,2*3))
nodes = [[0,0],[4,0],[2,3]]     #Node x and y coordinates
elem = [[0,1],[0,2],[2,1]]      #Node numbers bw which elements are created
Forces = [[0,0],[0,0],[5,-10]]
for i,e in enumerate(elem):
    L.append(elemlength(nodes[e[0]],nodes[e[1]]))
    T.append(angle(nodes[e[0]],nodes[e[1]]))
    k.append(elemstiff(E,A,L[i],T[i]))
    Globalstiff(K,k[i],e[0],e[1])
    print(K)

[[ 5250.     0. -5250.     0.     0.     0.]
 [    0.     0.     0.     0.     0.     0.]
 [-5250.     0.  5250.     0.     0.     0.]
 [    0.     0.     0.     0.     0.     0.]
 [    0.     0.     0.     0.     0.     0.]
 [    0.     0.     0.     0.     0.     0.]]
[[ 7042.10832627  2688.1624894  -5250.             0.
  -1792.10832627 -2688.1624894 ]
 [ 2688.1624894   4032.2437341      0.             0.
  -2688.1624894  -4032.2437341 ]
 [-5250.             0.          5250.             0.
      0.             0.        ]
 [    0.             0.             0.             0.
      0.             0.        ]
 [-1792.10832627 -2688.1624894      0.             0.
   1792.10832627  2688.1624894 ]
 [-2688.1624894  -4032.2437341      0.             0.
   2688.1624894   4032.2437341 ]]
[[ 7.04210833e+03  2.68816249e+03 -5.25000000e+03  0.00000000e+00
  -1.79210833e+03 -2.68816249e+03]
 [ 2.68816249e+03  4.03224373e+03  0.00000000e+00  0.00000000e+00
  -2.68816249e+03 -4.03224373e+03]
 [-5

In [8]:
k

[array([[ 5250.,     0., -5250.,    -0.],
        [    0.,     0.,    -0.,    -0.],
        [-5250.,    -0.,  5250.,     0.],
        [   -0.,    -0.,     0.,     0.]]),
 array([[ 1792.10832627,  2688.1624894 , -1792.10832627, -2688.1624894 ],
        [ 2688.1624894 ,  4032.2437341 , -2688.1624894 , -4032.2437341 ],
        [-1792.10832627, -2688.1624894 ,  1792.10832627,  2688.1624894 ],
        [-2688.1624894 , -4032.2437341 ,  2688.1624894 ,  4032.2437341 ]]),
 array([[ 1792.10832627, -2688.1624894 , -1792.10832627,  2688.1624894 ],
        [-2688.1624894 ,  4032.2437341 ,  2688.1624894 , -4032.2437341 ],
        [-1792.10832627,  2688.1624894 ,  1792.10832627, -2688.1624894 ],
        [ 2688.1624894 , -4032.2437341 , -2688.1624894 ,  4032.2437341 ]])]

[array([[ 5250.,     0., -5250.,    -0.],
        [    0.,     0.,    -0.,    -0.],
        [-5250.,    -0.,  5250.,     0.],
        [   -0.,    -0.,     0.,     0.]]),
 array([[ 1792.10832627,  2688.1624894 , -1792.10832627, -2688.1624894 ],
        [ 2688.1624894 ,  4032.2437341 , -2688.1624894 , -4032.2437341 ],
        [-1792.10832627, -2688.1624894 ,  1792.10832627,  2688.1624894 ],
        [-2688.1624894 , -4032.2437341 ,  2688.1624894 ,  4032.2437341 ]]),
 array([[ 1792.10832627, -2688.1624894 , -1792.10832627,  2688.1624894 ],
        [-2688.1624894 ,  4032.2437341 ,  2688.1624894 , -4032.2437341 ],
        [-1792.10832627,  2688.1624894 ,  1792.10832627, -2688.1624894 ],
        [ 2688.1624894 , -4032.2437341 , -2688.1624894 ,  4032.2437341 ]])]